# Generated by Django 5.2.8 on 2025-12-24 04:21
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_tags'),
    ]

    operations = [
        TrigramExtension()
    ]
